import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head';
import ThemeRegistry from './ThemeRegistry';
import BaseLayout from '@/layouts/Base'
const inter = Inter({ subsets: ['latin'] })
import { ModeProvider } from "./providers";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Head>
        <title>Hexabase CSV</title>
        <meta http-equiv="Content-Security-Policy" content="default-src *;
          img-src * 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' *;
          style-src  'self' 'unsafe-inline' *"></meta>
        <meta name="description" content="Hexabase import csv" />
      </Head>
      <body className={inter.className}>
        <ModeProvider>
        <ThemeRegistry  options={{ key: 'mui' }}>
          <BaseLayout>
            {children}
          </BaseLayout>
        </ThemeRegistry>
        </ModeProvider>
        </body>
    </html>
  )
}
